# -*- coding: utf-8 -*-

from django.test import TestCase, override_settings
import yaml
import pytest

from lily.base.conf import Config
from lily.base.utils import normalize_indentation


class ConfigTestCase(TestCase):

    @pytest.fixture(autouse=True)
    def initfixtures(self, tmpdir):
        self.tmpdir = tmpdir

    def test_properties(self):

        config_file = self.tmpdir.mkdir('conf').join('config.yaml')
        config_file.write(yaml.dump({
            'name': 'hello',
            'repository': 'bithub',
            'version': '0.1.9  # THIS LINE WAS AUTOGENERATED',
            'last_commit_hash': '940594',
        }))

        with override_settings(LILY_CONFIG_FILE_PATH=str(config_file)):
            config = Config()

            assert config.name == 'hello'
            assert config.repository == 'bithub'
            assert config.version == '0.1.9'
            assert config.last_commit_hash == '940594'

    def test_path(self):

        config_file = self.tmpdir.mkdir('conf').join('config.yaml')
        config_file.write(yaml.dump({
            'name': 'hello',
            'repository': 'bithub',
            'version': '0.1.9  # THIS LINE WAS AUTOGENERATED',
            'last_commit_hash': '940594',
        }))
        with override_settings(LILY_CONFIG_FILE_PATH=str(config_file)):
            config = Config()

            assert config.path == str(config_file)

    def test_version_setter(self):
        config_file = self.tmpdir.mkdir('conf').join('config.yaml')
        config_file.write(yaml.dump({
            'name': 'hello',
            'repository': 'bithub',
            'version': '0.1.9',
            'last_commit_hash': '940594',
        }))

        with override_settings(LILY_CONFIG_FILE_PATH=str(config_file)):
            Config().version = '0.1.21'

        with open(str(config_file), 'r') as f:
            assert f.read() == normalize_indentation('''
                name: hello
                version: 0.1.21  # THIS LINE WAS AUTOGENERATED, ALL MANUAL CHANGES CAN BE OVERWRITTEN
                repository: bithub
                last_commit_hash: 940594  # THIS LINE WAS AUTOGENERATED, ALL MANUAL CHANGES CAN BE OVERWRITTEN
            ''', 0) # noqa

    def test_last_commit_hash_setter(self):
        config_file = self.tmpdir.mkdir('conf').join('config.yaml')
        config_file.write(yaml.dump({
            'name': 'hello',
            'repository': 'bithub',
            'version': '0.1.9',
            'last_commit_hash': '940594',
        }))

        with override_settings(LILY_CONFIG_FILE_PATH=str(config_file)):
            Config().last_commit_hash = '9405943abc'

        with open(str(config_file), 'r') as f:
            assert f.read() == normalize_indentation('''
                name: hello
                version: 0.1.9  # THIS LINE WAS AUTOGENERATED, ALL MANUAL CHANGES CAN BE OVERWRITTEN
                repository: bithub
                last_commit_hash: 9405943abc  # THIS LINE WAS AUTOGENERATED, ALL MANUAL CHANGES CAN BE OVERWRITTEN
            ''', 0) # noqa
