
name: lily
description: Lily MicroService Framework for Humans
author: CoSphere Tech Team
repository: https://bitbucket.org/goodai/lily

# -- FIXME: !!!!!! this would have to be filled automatically
version: 0.1.24
last_commit_hash: 3b0510aac88ab61f3146237a58db8e5b74dfdaa4
