name: lily - test and publish

on: push

jobs:
  test-and-push:
    name: Unit Tests - working branch
    runs-on: ubuntu-latest
    environment: production

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: lily
          POSTGRES_PASSWORD: mysecret
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5435:5432/tcp

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          architecture: "x64"

      - name: Install Poetry
        uses: Gr1N/setup-poetry@v7

      - name: Display Python and Poetry versions
        run: |
          python --version
          poetry --version

      - name: Install dependencies
        working-directory: .
        run: |
          sudo apt-get update
          sudo apt-get install -y libhunspell-dev hunspell hunspell-pl
          poetry env use 3.9.9
          poetry install

      - name: Launch linter
        working-directory: .
        run: poetry run make lint

      - name: Launch tests
        working-directory: .
        run: poetry run make test_all

      # if launched from master branch, then build and publish to PyPI
      - name: Build and publish
        if: github.ref == 'refs/heads/master'
        working-directory: .
        run: |
          git tag $(poetry version -s)
          git push origin --tags
          poetry publish --build -u __token__ -p ${{ secrets.PYPI_LILY_API_TOKEN }}
